### ISSUE TITLE
Any help file avaiable?

### ISSUE THREAD

**Issue by Desantowski** [Bartozzz/Qilin#28]
I don't know how to compile or run preview using Qilin, is there any help file, readme or menu? I use Windows version of application.

**Comment by Bartozzz** [comment]
Right now there is no context menu, because I don't have the time to normalize it for each OS (problems with dark mode on Windows and Linux due to [nw.js](https://nwjs.io/) limitations). There are some resources which may help you:
- I've created a small [Wiki](https://github.com/Bartozzz/Qilin/wiki). Right now it is in its early stages as it only contains informations about **shortcuts** and **syntax**, but I'll try to keep it up-to-date and add more informations for beginners.
- I've also uploaded a new release - [v0.2.0-alpha](https://github.com/Bartozzz/Qilin/releases/tag/v0.2.0-alpha), which includes **Math Formula Editor** to help people write formulas with a simple, visual editor. It might be a little messy but I am still working on it.

I am not sure about the preview though, but it might be a bug with KaTeX parser. Anyway, it works in the new release. Let me know if you have any other questions so I can answer you and eventually create another page on the Wiki.
